IMAGE = "debian/bullseye64"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.hostname = "traefik-docker"
  config.vm.network  :private_network, ip: "10.0.0.30"
  config.vm.provision "shell", privileged: true,  path: "../../scripts/docker_install.sh"
  config.vm.provision "shell", privileged: true,  path: "../../scripts/docker-compose_install.sh"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 22, host: 22
  config.vm.network "forwarded_port", guest: 8443, host: 8443
end