apiVersion: v1
kind: Service
metadata:
 name: traefik
 namespace: traefik
spec:
 type: LoadBalancer
 selector:
   k8s-app: traefik
   app: traefik
 ports:
 - port: 8080
   targetPort: 8080
   name: traefik
 - port: 443
   targetPort: 443
   name: https
 - port: 80
   targetPort: 80
   name: http