Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "traefik-k3s"
  config.vm.network  :private_network, ip: "10.0.0.30"
  config.vm.provision "file", source: "../../provisionning/k3s/", destination: "/home/vagrant/"
  config.vm.provision "shell", privileged: true, path: "../../scripts/docker_install.sh"
  config.vm.provision "shell", privileged: true, path: "../../scripts/k3s_install.sh"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |v|
	v.memory = 2048
  end
end